import { LogoutButton } from '@/app/Logout';
import { AuthProvider } from '@/context/AuthProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthProvider>
                    <nav className="p-4 bg-gray-800 text-white flex space-x-4">
                        <Link href="/">🏠 Main</Link>
                        <Link href="/auth/login">🔐 Logi </Link>
                        <Link href="/auth/register">📝 Registration</Link>
                        <Link href="/users/profile">📌 Profile</Link>
                        <LogoutButton />
                    </nav>
                    <main className="p-4">{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
